
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres       # Superuser
      POSTGRES_PASSWORD: postgres   # Superuser password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 15

  app:
    build: .
    env_file: .env
    environment:
      MODE: production
      DATABASE_URL: postgresql://vongaimusvaire:MySushi32@db:5432/echo_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:
