services:
  - type: web
    name: echoiq
    env: docker
    dockerfilePath: Dockerfile
    plan: free  # or 'starter', 'standard' based on your needs
    buildCommand: docker build -t echoiq .
    startCommand: docker run -p 10000:8000 -e DATABASE_URL=$DATABASE_URL echoiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: echo_db_h8cz  # Matches your Render DB name
          property: connectionString
      - key: MODE
        value: production
    healthCheckPath: /health  # Recommended to add a health check endpoint
    autoDeploy: true  # Optional: automatic deploys on git push